name: Release

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/release.yml
      - "**.nix"
      - flake.lock

env:
  REGISTRY: ghcr.io

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Check Flake
        run: nix flake check

  get-images:
    needs: check
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.get-images.outputs.images }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - id: get-images
        run: |
          nix flake show --json --quiet --quiet \
            | jq -r '.packages["x86_64-linux"] | delpaths([["default"],["geolite2"]]) | keys | "images=" + (. | tostring)' \
            >> $GITHUB_OUTPUT

  build-and-push:
    needs: get-images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.get-images.outputs.images) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ${{ matrix.image }}
        run: |
          IMAGE_ID=$(nix run ".#${{ matrix.image }}.copyToDockerDaemon" | grep "Copy to Docker daemon" | cut -d' ' -f6)
          LATEST_ID=$(sed 's/^\(.*:\)[0-9]\+\(\.[0-9]\+\)\{2\}\(.*\)$/\1latest\3/' <<< $IMAGE_ID)
          REPO="${{ env.REGISTRY }}/${{ github.repository }}"
          TAG="$REPO/$IMAGE_ID"
          LATEST_TAG="$REPO/$LATEST_ID"

          docker tag "$IMAGE_ID" "$TAG"
          docker tag "$IMAGE_ID" "$LATEST_TAG"
          docker push "$TAG"
          docker push "$LATEST_TAG"

          if [[ "$IMAGE_ID" =~ geolite2(-[0-9]+){3} ]]; then
            LATEST_GEOLITE2_ID=$(sed 's/\(.*\)\(geolite2\)\(-[0-9]\+\)\{3\}\(.*\)/\1\2\4/' <<< $IMAGE_ID)
            LATEST_GEOLITE2_TAG="$REPO/$LATEST_GEOLITE2_ID"

            docker tag "$IMAGE_ID" "$LATEST_GEOLITE2_TAG"
            docker push "$LATEST_GEOLITE2_TAG"
          fi
